### ISSUE TITLE
关于Menu的Tip的小问题

### ISSUE THREAD

**Issue by stevei5mc** [MemoriesOfTime/RsNPC#43]
这个小问题是我之前就发现的
如图所示
![rsnpc](https://github.com/user-attachments/assets/4b550e3d-9567-47e4-bf49-00194a7d8996)
这一段消息并不会在中秋节当天显示，而是在8月份的15号显示，这个问题虽然没有影响，但是给人有一种怪怪的感觉

如果能够实现农历和公历之间的转换的话应该就能添加更多的小提示了

**Comment by lt-name** [comment]
目前来看，似乎没必要为了一个彩蛋内容塞进去一套阳历阴历转换库，所以打算删除这段

**Comment by stevei5mc** [comment]
这样子来看确实没有必要单单为这一条消息就搞的那么复杂
